post http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "minh123@gmail.com",
    "password": "123123"
}

################################
post http://localhost:5000/api/project/617a8a2294c4f71098cdd4ff/share
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGQzOTNmZTAyMDYzMTIyYzBmYjM0MCIsImlhdCI6MTYzNjE5ODA1NiwiZXhwIjoxNjM2Mjg0NDU2fQ.EEx0jIgE_nPrftznE1jZHDBNsCCmrAhVuDt-my7Olkc
Content-Type: application/json

[
"610f9fe2f1588d4abca1a940",
"610f9fe2f1588d4abca1a940",
"610f9fe2f1588d4abca1a940"
]